/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ScrollDirection {
  Down = 0,
  Up = 1,
}
export const enum MouseButton {
  Left = 0,
  Middle = 1,
  Right = 2,
}
export const enum KeyboardKey {
  Num0 = 0,
  Num1 = 1,
  Num2 = 2,
  Num3 = 3,
  Num4 = 4,
  Num5 = 5,
  Num6 = 6,
  Num7 = 7,
  Num8 = 8,
  Num9 = 9,
  A = 10,
  B = 11,
  C = 12,
  D = 13,
  E = 14,
  F = 15,
  G = 16,
  H = 17,
  I = 18,
  J = 19,
  K = 20,
  L = 21,
  M = 22,
  N = 23,
  O = 24,
  P = 25,
  Q = 26,
  R = 27,
  S = 28,
  T = 29,
  U = 30,
  V = 31,
  W = 32,
  X = 33,
  Y = 34,
  Z = 35,
  Add = 36,
  Subtract = 37,
  Multiply = 38,
  Divide = 39,
  OEM2 = 40,
  Tab = 41,
  CapsLock = 42,
  Shift = 43,
  Control = 44,
  Alt = 45,
  Space = 46,
  Backspace = 47,
  Return = 48,
  Escape = 49,
  UpArrow = 50,
  DownArrow = 51,
  LeftArrow = 52,
  RightArrow = 53,
  Meta = 54,
}
export interface Point {
  x: number
  y: number
}
export interface ToggleKey {
  value: KeyboardKey
  down: boolean
}
export type EnigoJs = Enigo
export class Enigo {
  constructor()
  /**
   * Returns a list of all currently pressed keys.
   *
   * ### Example
   * ```js
   * import { Enigo } from '@enigo-js/core'
   *
   * const enigo = new Enigo();
   * const keys = enigo.held();
   * console.log(keys);
   * ```
   *
   * @returns {Array<Key>} keys - The list of currently pressed keys.
   */
  held(): Uint16Array
  getMousePosition(): Point
  setMousePosition(x: number, y: number): void
  setButtonClick(button: MouseButton): void
  setButtonToggle(button: MouseButton, down: boolean): void
  setMouseScroll(direction: ScrollDirection, clicks: number): void
  typeText(content: string): void
  pressKey(keys: Array<KeyboardKey>): void
  releaseKey(keys: Array<KeyboardKey>): void
}
